### PR TITLE
Use the return value of GCIntersectSegment

### PR DESCRIPTION
**Pull request by Rasbats**
Tidying up. 
By using the return value of true if the lines intersect we have the same way of working as the original code. If no intersection the code has other work to do which was bypassed before this PR

### CODE REVIEW

**Comment by rgleason** [comment]
Mike, yesterday I did some testing in the area of japan after confirming operation in Adriatic, and I found some issues. The laylines partially worked but when tacking to the other tack, they went screwy. 
Will this fix that problem?

**Comment by Rasbats** [comment]
"Will this fix that problem?"
I don't think so. But please test again.

**Comment by Rasbats** [comment]
Every time I install from Cloudsmith the plugin crashes when enabled. Do you have another build from laylines branch?

**Comment by rgleason** [comment]
Mike, next time, before you push, if you can increment the last version digit "tweak"  in the top of the CMakeLists.txt file, then there will be a different version number in the alpha branch made, when the PR is merged. It will help us.

I haven't noticed that problem, crashing when tactics is enabled, but I will test that more.

**Pull request merged**
